apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-publisher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: market-data-publisher
  template:
    metadata:
      labels:
        app: market-data-publisher
    spec:
      containers:
      - name: market-data-publisher
        image: market-data-publisher:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3003
        resources:
          requests:
            cpu: "100m"      
            memory: "128Mi"   
        livenessProbe:
          httpGet:
            path: /
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3003
          initialDelaySeconds: 3
          periodSeconds: 5
