apiVersion: v1
kind: Service
metadata:
  name: market-data-publisher
spec:
  selector:
    app: market-data-publisher
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
