apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manager
spec:
  replicas: 7
  selector:
    matchLabels:
      app: order-manager
  template:
    metadata:
      labels:
        app: order-manager
    spec:
      containers:
      - name: order-manager
        image: order-manager:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: "200m"      
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 2


